version: '3'
services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/php/php.development.ini:/usr/local/etc/php/conf.d/php.development.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - network
        links:
            - db
        extra_hosts:
            - host.docker.internal:host-gateway

    ####################################################################################################
    # Nginx
    ####################################################################################################
    web_server:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network
        depends_on:
            - app



    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8089:80"
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
            - network
        volumes:
            - app_name_phpmyadmin:/sessions

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: 'axllent/mailpit:latest'
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - network
        volumes:
            - app_name_mailpit:/data
        environment:
            MP_MAX_MESSAGES: 1000
            MP_DATABASE: /data/mailpit.db

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        ports:
            - "${REDIS_PUBLISHED_PORT:-6379}:6379"
        networks:
            - network
        volumes:
            - app_name_redis:/data

    # ####################################################################################################
    # DATABASE (MariaDB)
    # ####################################################################################################
    db:
       image: mariadb:latest
       environment:
       MYSQL_ROOT_PASSWORD: Annaaremere!1
       MYSQL_DATABASE: legalmente_prod
       MYSQL_USER: legalmente_user
       MYSQL_PASSWORD: 2-ua$9hQ26T/
       networks:
            - network
        volumes:
            - app_name_db:/var/lib/mysql
            - ./docker/mysql/logs:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf


    # pgAdmin
    ####################################################################################################
    #pgadmin:
    #    image: dpage/pgadmin4
    #    ports:
    #        - "5050:80"
    #    environment:
    #        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #        - PGADMIN_DEFAULT_PASSWORD=password
    #    depends_on:
    #        - db
    #    networks:
    #        - network

#Docker Networks
networks:
    network:
        driver: bridge
volumes:
    app_name_db: { }
    app_name_mailpit: { }
    app_name_phpmyadmin: { }
    app_name_redis: { }
